# Mon  6 Apr 11:14:17 2020

## Manuscript

- What am I looking to address / question am I posing in the introduction?
- Literature review: Methodologies?
  - SMC? Not a specification tool, although D&C SMC is close
- Literature review: Applications?
  - Ecology IPMs are good
  - What else?

## Mathematics

- I think most of the mathematics in the early sections is correct, but it lacks a point. 
  - Why am I presenting this?
  - If you don't consider the middle model prior jointly, then strange things happen depending on the order of melding? 
    - Why is the order suddenly coming into this?

## Multistage samplers

- Change all to M = 3 case, move general M = M case to appendix.
- Note advantages in the text, disadvantages in the discussion
  - Can detect conflict in sequential sampler
  - Distributed sampler can be faster? Submodels done in parallel.


## Examples

### Little owls

- Make sure $\phi_{1 \cap 2} = (\alpha_{0}, \alpha_{2})$ and notation is correct everywhere (i.e. just the intercept and Juvenile/Adult term that parameterises $\phi$, the gender term isn't in the capture/recapture submodel).
- Technically not doing the prior for $p_{1}(\phi_{1 \cap 2})$ and $p_{2}(\phi_{1 \cap 2})$ correctly, currently doing product of experts implicitly.

- Results: 
  - What tone should I take in the results section?
  - What do we want to highlight?
    - That we get the same results as the IPM?
    - Illustrates that we can use samples from the submodels / subposteriors in future samplers to target a joint model that we never explicitly evaluate? 

- Sampler needs better detailing, as does method.

### Other example

- Need to find, was going to talk to Nick's friend Michelle?
- Primary strategy here was to talk to Anne, but she is now pretty busy, and likely will be for a number of months.
- Need a genuine joining example