---
title: "Response to Reviewers"
author: "Andrew A. Manderson and Robert J. B. Goudie"
date: "`r format(Sys.time(), '%d %B, %Y')`"
fontfamily: tgpagella
fontsize: 10pt
papersize: a4
geometry: margin=2.25cm
bibliography: ../bibliography/multi-phi-bib.bib
csl: ../bibliography/journal-of-the-royal-statistical-society.csl
link-citations: true
hyperrefoptions:
  - backref
  - colorlinks=true
output:
  pdf_document:
    includes:
      in_header:
        ../tex-input/pre.tex
    fig_caption: true
    number_sections: true
    keep_tex: true
---

<!--
Rscript -e 'rmarkdown::render("ba-reviews/2022-03_response.rmd")'
-->

# Reviewer 1 {-}

> $\hookrightarrow$**R1**: _My main suggestion is for the authors to shorten the manuscript by moving one of the examples to an appendix and instead add a bit more detail about how the melding actually works for readers who may not have familiarity with the previous literature on the topic (including the authors' prior paper on it).  I appreciate both examples in the manuscript, but it might be better to include details about when the pooling results in inference that is exact versus approximate, for example.  There are many choices one must make to implement these methods for fitting models and I think it would help to provide some additional details about the approximation that occurs and the actual algorithms that are used (multi-stage) to fit the models using this approach which don't currently appear until the appendix._

We thank the reviewer for the kind comments.
We will respond in reverse order to the points raised by Reviewer 1.

We agree that there are many choices to make when implementing chained Markov melding, but we delineate between choices specific to chained Markov melding and those that must be made when fitting any model.
We wish to include in the main text the choices that we feel will _always_ be important in applications of chained Markov melding, with related, but ultimately example-specific, choices included in the appendix.
To this point we have clarified the purposes of the appendices in the text, and explicitly stated the choices specific to chained Markov melding that users must make.
Our changes are:

1. Adding a sentence to the end of paragraph 1 of the conclusion to that reads:

    "_We also present the choices, and their impacts, that users of chained Markov melding must make which include: the choice of pooling function, and where required the pooling weights; the choice of posterior sampler and the design thereof, including the apportionment of the pooled prior over the stages and stage-specific MCMC techniques._"

1. Emphasising in the text and within the appendix that the individual-at-a-time sampler is only possible due to the conditional independence between individuals in the posterior. Appendix K establishes the validity of our sampler, but the argument is specific to the submodels in the second example (though other submodels may have such posterior conditional independences). The general applicability of the individual-at-a-time sampler is low, so including it in the main text seems unnecessary and likely to confuse the reader. Specifically, we have added a sentence in Section 5.5 that reads:

    "_This is possible due to the conditional independence between individuals in the posterior, and Appendix K contains the details of this scheme._"

    and modified subsection "sub-step 1" of Appendix K to include:

    "_The model, detailed in Section 5.1, uses the conditional independence between individuals to factorise such that \textellipsis_".

1. Noting in the main text that Appendix B is provided only for completeness. We do not use the sequential sampler in either of our examples. The footnote on page 13 now reads:

    "_For completeness, Appendix B describes such a sequential MCMC sampler. We do not use the sequential sampler in this paper._"

Furthermore, we think that Appendices E, G, and H, covering prior specification and prior marginal estimation, are important but ultimately routine aspects of Bayesian modelling.
Appendices D and I are decisions specific to the data we consider, and would be made as part of any analysis of observational data (and would often go unreported), or would be specified in an analysis plan.

We are unsure of the meaning of the comment describing pooling as producing inference that is exact or approximate.
When all prior marginal densities are known analytically, the pooling function produces an analytic expression proportional to $\pd_{\text{pool}}(\boldsymbol{\phi})$ -- there is no approximation error here.
If one or more of the prior marginal densities is unknown, then we suggest approximating it with a standard distribution or using kernel density estimation. Regardless, the pooling function does not introduce any approximation in addition to that of the prior marginal density estimate.
If by 'exact' the reviewer is instead referring to situations where the chained Markov melded model is the same as the original joint model, then we wish to point our that a suitable joint model must exist in the first place (see our response to Reviewer 2 for further details).
Our first example is one such situation, and we have added the following to the start of Section 4:

- "_This example is particularly interesting to us as, for a certain choice of pooling function and pooling weights, the chained Markov melded model and the IPM are identical. This coincidence allows us to use the posterior from the IPM as a benchmark for our multi-stage sampler._"

and the following (new in italic) to Section 4.5:

- "We also use logarithmic pooling with $\lambda = (\frac{1}{2}, \frac{1}{2}, \frac{1}{2})$, which is denoted $\pd_{\text{meld, log}}$ _and results in the chained melded model being identical to the IPM._"

To address Reviewer 1's first comment, we appreciate  the inclination towards a shorter manuscript, but ultimately feel tied to including both examples in the main text.
As Reviewer 2 notes, the first example is intentionally illustrative -- we have split an existing joint model to make clear, in a simpler setting, the chained Markov melding steps and proposed computational tools, whilst possessing a baseline result for comparison.
This example is also intended to reassure the reader that our proposed multi-stage sampler can produce accurate results.
Whilst we find this example informative, it is ultimately insufficiently compelling to justify the methodology.
The second example is much more compelling for the methodology, and as Reviewer 2 notes it is the example's complexity that motivates the methodology.
If such complex submodels were not necessary we might be able to immediately conceive of a joint model for all sources of data.
Without the second example we feel some readers will be left wondering what use, if any, there might be for our method.
Finally, moving the first example to the appendix would save only 4 pages, so information currently in the appendix would remain there in either case.

We hope that these points, in addition to addressing the reviewers other comments, sufficiently convince the reviewer of the need for both examples.

> $\hookrightarrow$**R1**: _I also have a number of minor typographical suggestions:_

We thank the reviewer for the suggestions and have adopted them in the revised version.

# Reviewer 2 {-}

We thank the reviewer for the kind comments.

> $\hookrightarrow$**R2**: _(2) I would like the authors to explain why one would not simply ensure that all sub-models can use the same prior, so that we are back in the "Markov combination" setting of Equation 1 (in which case no "pooled" priors need to be constructed). It seems to me that a principled Bayesian approach would always seek to formulate a single prior distribution over all parameters in the model._

We agree in principle with this sentiment -- it seems desirable to have the same prior for the same quantity in different models.
But there is a tension between having the individual submodels be complete and contained, meaning that they could be specified and understood independently of the chained melded model, and having the same prior for all common quantities under all submodels.
It is of course theoretically possible to specify $\pd_{\text{pool}}(\boldsymbol{\phi})$ to be something other than a function of the submodel marginals -- a "BYO-prior" if you will.
The tricky question here is how one acquires this prior and ensures that it is suitable for the chained melded model, and all its marginals are suitable for the submodels.
As we note in the second sentence of the introduction, the difficulty in modelling multiple sources of information is specifying a suitable joint model, which includes specifying the prior for such a joint model.
We choose to specify a prior using pooling because we find it hard, particularly as $\Nm$ increases, to obtain a prior suitable for the chained melded model and with suitable marginals, as well as embedding appropriate covariance between the neighbouring components of $\boldsymbol{\phi}$ which we consider important.
More generally, we see the competing methodology for example two as not a full Bayesian joint model, but simply plugging-in a point estimate, or Gaussian approximation, of the common quantities [e.g. Section 4.2.4 of @nicholson_interoperability_2021].
Our aim is to facilitate the specification of more sophisticated models from components/submodels that modellers likely already possess, and ease the sometimes onerous burden of prior specification.

We also foresee some technical difficulties in unifying the prior across submodels, if we take as a starting point the existence of the submodels and suitably defined common quantities.
In particular, perhaps our biggest struggle with this idea is visible in example two, where the common quantity $\phi_{1 \cap 2}$ is the response in the second submodel $\pd_{2}(\phi_{1 \cap 2}, \phi_{2 \cap 3}, \psi_{2}, Y_{2})$ and $\pd_{2}(\phi_{1 \cap 2}, \phi_{2 \cap 3})$ contains dependence between the common quantities.
We see two approaches to ensuring $\pd_{1}(\phi_{1 \cap 2}) = \pd_{2}(\phi_{1 \cap 2})$, $\pd_{2}(\phi_{2 \cap 3}) = \pd_{3}(\phi_{2 \cap 3})$, and $\pd_{1}(\phi_{1 \cap 2})\pd_{3}(\phi_{2 \cap 3}) = \pd_{2}(\phi_{1 \cap 2}, \phi_{2 \cap 3})$ in example two.

  1. Carefully and simultaneously select the prior for the spline coefficients in $\pd_{1}$ and the prior for the piecewise-linear regression parameters in $\pd_{3}$, such that all the aforementioned equalities are satisfied.

We note here that there are no guarantees that such a set of priors exists[^prior-by-ppd], and even if they did it's unclear how we might actually specify them.

  2. Externally define $\pd_{\text{pool}}(\boldsymbol{\phi})$ and replace $\pd_{1}(\phi_{1 \cap 2})$ with $\pd_{\text{pool}}(\phi_{1 \cap 2})$, $\pd_{2}(\phi_{1 \cap 2}, \phi_{2 \cap 3})$ with $\pd_{\text{pool}}(\boldsymbol{\phi})$, and $\pd_{3}(\phi_{2 \cap 3})$ with $\pd_{\text{pool}}(\phi_{2 \cap 3})$. Alternatively we could expand $\pd_{1}$ to be aware of $\pd_{3}$ by replacing $\pd_{1}(\phi_{1 \cap 2})$ with $\pd_{\text{pool}}(\boldsymbol{\phi})$, doing likewise for $\pd_{3}$.

Both proposals require some kind of pooling to account for applying the prior twice when combining the submodels, should such a correction be desirable.
The second proposal requires expanding the first and third submodels to include a quantity unrelated to the submodel or the submodel's data. There is no information about e.g. $\phi_{2 \cap 3}$ in $\pd_{1}$.
This submodel expansion makes it more difficult to understand the submodels in isolation.
One aim of our methodology is to enable the construction of complex joint models by combining smaller, easier to understand submodels.
The ability to specify, and possibly fit and interrogate a submodel before combining it is key -- we'd like to understand the submodels themselves before combining them.
Either option in the second proposal yields a very strange form for $\pd_{2}$, which would contain a prior term, in addition to the likelihood, directly for the observational quantity as well as the prior terms for the other parameters.
Whilst many of these properties are also true of the chained melded model, the key difference is that the submodels remain unmodified and are understandable in isolation.

There are also no guarantees that a prior that "works" for the submodel (appropriately represents known information and facilitates the computation of the subposterior) will be suitable for the chained melded model with its higher dimensional parameter space.
Pooling allows us to take known priors and modify them in a transparent way to ensure they are suitable for the larger chained melded model.

[^prior-by-ppd]: In our experience there are typically many possible priors that have a specific prior predictive distribution for a quantity that is a non-invertible transformation of the parameters. Locating them requires both specialised methodology and a decision analysis to choose between the possible priors.

\par\noindent\hrulefill\par

We address points (3) and (4) simultaneously.

> $\hookrightarrow$**R2**: _(3) The proposed methodology appears to perform well in the integrated-population-model (IPM) example. But, as the authors mention, this is just for illustration since the joint posterior distribution in this model can be easily and cheaply approximated using a single MCMC chain via standard software packages._
> _The model in Section 5 appears to be realistically complex. It is great to see such non-toy examples in a methodological paper. However, the example is almost too complex: I am finding it difficult to understand how well (or poorly) the proposed methodology performs here. It would be really good to have benchmark results for the joint model without the bias induced by Markov melding (i.e. in the same way as these are shown for the IPM example). I would expect that such results are be attainable using a sequential Monte Carlo sampler._

> $\hookrightarrow$**R2**: _(4) If benchmark results cannot be obtained for the model from Section 5, this would also be interesting and mentioning this would make the paper much stronger. Because when reading the paper, I did not see an explanation of why the model could not be estimated without Markov melding (and without the bias that this can introduce)._

To obtain benchmark results there must exist 1) a comparable joint model and 2) a proven method for sampling/approximating the posterior of this model.

With respect to the first prerequisite, the premise for this example, and indeed the methodology, is that there are situations in which it is prohibitively difficult to specify a suitable joint model.
Some of these difficulties are covered in our response to point (2).
The point we wish to make, and is a clear response to (4), is that there is no other existing joint model in this example, and that the joint model formed by multiplying the individuals submodels _is_ a form of chained Markov melding (using product-of-experts pooling).
Given this, we find find the meaning of 'bias induced by Markov melding' difficult to determine in this comment.
Chained Markov melding does not necessarily introduce any 'bias'.
As noted in the text for the first example, the IPM and the log-pooling with $\lambda = (\frac{1}{2}, \frac{1}{2}, \frac{1}{2})$ are precisely the same joint model, so no possible 'bias' has been introduced by chained Markov melding in that example.
When no other joint model exists there is no baseline against which results could be declared biased.
Additionally, in the PoE case, there is no bias due to finite-sample marginal density approximation as these terms all cancel in the second stage acceptance probability (so we do not use the marginal approximations).
If it is this type of bias the reviewer has in mind, then it is unclear to us what joint model the reviewer wishes to target.

For the second prerequisite, there are a number of additional difficulties to do with implementing such an SMC sampler (once a target/joint model has been decided upon)
1. Simultaneously evaluating all the terms in the chained melded model is necessary and computationally challenging in a SMC/MCMC environment. This is a secondary motivation for the sampler, as complex evidence synthesis / joint models often cannot be readily evaluated in this manner [see, for example, the models in @nicholson_interoperability_2021]. One complication of this variety in paper is the calculation of $\phi_{1 \cap 2} = (f(\chi_{1 \cap 2, 1}), \ldots, f(\chi_{1 \cap 2, N}))$. The mathematics belies much complexity, specifically because we rely on a multiple root finder. Implementing this within an HMC, or SMC with HMC refreshment, setting involves massively increasing the number of times this problem must be solved. Using our multi-stage sampler turns this into an embarrassingly parallel, post-stage-one processing problem.
1. Our preoccupation with HMC is because the example depends on a relatively high number ($5 \times 10^{4}$) of high-quality samples from $\pd_{1}(\phi_{1 \cap 2}, \psi_{1} \mid Y_{1})$, which is $N(2 + 10) = 444$-dimensional and highly correlated within each of the 12-dimensional individual subposteriors. This is made possible by the efficient dynamic HMC implementation within `Stan`.
1. There are no sufficiently flexible off the shelf SMC packages. `NIMBLE` [@michaud_sequential_2020] does not support either the B-spline basis function nor multiple-root finder, and whilst one could in theory recode both in `Rcpp` to make use of `RcppSMC` [@eddelbuettel_rcppsmc_2021; @johansen_smctc_2009], this would be an enormous undertaking. We also point out the difficult in implementing an SMC sampler for the considerably simpler first example encountered by @finke_efficient_2019 (with details discussed in the online appendix).
1. A complete set of numerical and visual diagnostics for the multistage samplers are contained in the online repository, should there be any concern about the MCMC performance.

With the above points in mind, we have made the following modifications to the manuscript to emphasise the key aspects of this example, including:

1. To the end of section 1.1 "_It is in examples such as this one that we foresee the most use for chained Markov melding; a fully Bayesian approach is desired and the submodels are non-trivial in complexity, with no previously existing or obvious joint model._"
1. To the end of the first paragraph of Section 5.1 "_The complexity of both the submodels and the definition of the event time complicates the specification of a joint model. Event times and indicators are a non-invertible function of other parameters in the first submodel, and are an uncertain response in the survival submodel. Chained Markov melding enables us to specify a suitable joint model despite these complications._"
1. As the new third and forth sentences of paragraph 2 in Section 5.5 "_Targeting_ $\pd_{1}(\phi_{1 \cap 2}, \psi_{1} \mid Y_{1})$ _in stage one alleviates the need to solve Equation (46) within an MCMC iteration, instead turning the production of_ $\phi_{1 \cap 2}$ _into an embarrassingly parallel, post-stage-one processing step. Attempting to sample the melded posterior directly would involve solving (46) many times within each iteration, presenting a sizeable computational hurdle which we avoid._"

# Handling Editor {-}

> $\hookrightarrow$**HE**: _On equation (42) what happens when_ $x_{t - 1} = 0$? _Shouldn't the notation accommodate this case?_

Strictly yes, assuming the issue is that the Poisson distribution is not typically defined when its parameter is equal to zero, but this model is ubiquitous and this issue is ubiquitously ignored [Section 17.3 of @king_statistical_2011; "Materials and methods" in @abadi_estimation_2010; Section 5.2.1 of @finke_efficient_2019].
Interestingly, the `R` developers choose to define $\text{Pois}(0)$ to be a point mass at $0$:

```{r}
rpois(n = 10, lambda = 0)
```

`Stan` explicitly throws an error for `poisson_rng(0.0)`, whilst `NIMBLE` will sample a node defined as `x ~ dpois(0.0)`
We have added the following sentence to the end of Section 4.2 reading

- "_If_ $x_{t - 1} = 0$ _then we assume that the Poisson and binomial distributions become point masses at zero._"

# Bibliography
