---
title: "Manuscript to do list"
author: "Andrew Manderson"
date: "`r format(Sys.time(), '%d %B, %Y')`"
fontfamily: tgpagella
fontsize: 10pt
papersize: a4
geometry: margin=2.25cm
bibliography: ../bibliography/multi-phi-bib.bib
csl: ../bibliography/journal-of-the-royal-statistical-society.csl
output: 
  html_document:
    code_folding: hide
---

```{r setup, include = FALSE, cache = FALSE, message = FALSE, warning = FALSE, comment = NA}
options(width = 9999)
knitr::opts_chunk$set(echo = TRUE, cache = TRUE)
```

- [ ] change github link for zenodo doi
- [ ] write abstract and use to submit to conferences

# introduction

- [ ] pragmatism argument
- [ ] introduction to other relevant bits of literature
- [ ] very clear on what the contributions of this work are
    - _this will take a number of re works, so I don't have to get it perfect each time_

# Example introduction

- [] the submodels should include their parameter arguments here -- we can drop them later
- [x] the tikz pictures should have the $\phi$'s duplicated and separated into each submodel so that we can see the problem not the solution.
- [ ] acknowledge the first example is not necessarily surprising
- [ ] submodels are not really independent, find a different descriptor
- [ ] change third model to something that acknowledges the threshold regression idea, but without the stochastic process.
- [x] introduce the survival example 
- [x] emphasise why each of the examples is interesting / what angle of the problem it explores.
    - [x] IPM is the simplest real example of the type of modelling we are interested in
    - [x] Survival is another example of a type of modelling that is currently happening, but may be conceptually easier in our proposed framework.

# Model specification

- [x] things like 'appropriate joint model' and 'valid joint density' are imprecise and should be removed
- [-] ~~don't think using the word 'adjacent' / describing it is worth the effort.~~
    - I later think otherwise
- [x] bit more specific about the conditions for the submodels
    - [ ] this is covered in 3.2
- [x] '(co)variance \sigma' is not correct
- [x] missing closing parentheses after Equation (7)

# model coherency

- [ ] some of these results are wrong (specifically 3ii). I need to figure out what exactly I want to say (still unclear) and how exactly one might prove such a a thing.
- [x] rewrite
    - [x] decide if we should use \cap in this section
        - no.
- [x] cut conditional commutativity
- [ ] decide if this goes in the appendix or in the main text
    - I want this in the main text of the thesis, but I'm not sure what it adds to the paper.

- [ ] I think there is a way to make the Externally Bayesian argument make sense.

# posterior estimation

- [ ] citations for multi-stage samplers 
- [x] include normal approximations an propagation of point estimates 
- [ ] is the maths really necessary? might be worth putting into the appendix and just summarising in the main text
    - yes

# examples

- [ ] I do think one of these examples needs to use a pooled prior that isn't PoE -- I guess ideally some combination of all of them? This is HPC job.
- [x] Figure 6 needs a legend (owls example)

- [ ] emphasises that the examples are proofs of existence / people already modelling in this manner 
- [x] the second model can't really be done as a joint model? You'd have to do some form of gibbs? nah, but it would be difficult to get it all working simultaneously.
- [x] the work to get the second example working / showing what we want it to show.
- [x] the effect sizes in the survival setting need to be reduced 

# conclusion

- [ ] 7.2 and 7.3 are subs of 7.1
- [ ] 7.5 is probably not worth discussing again.
- [ ] 7.7 is the most interesting imo
- [ ] 7.6 is worth discussing and citing.

# Appendices

- [ ] Add math justification from weekly report for individual at a time updating.
